num = int(input())

print('-' * 12)
a = print('{} x {:2} = {}'.format(num, 1, num * 1))
b = print('{} x {:2} = {}'.format(num, 2, num * 2))
c = print('{} x {:2} = {}'.format(num, 3, num * 3))
d = print('{} x {:2} = {}'.format(num, 4, num * 4))
e = print('{} x {:2} = {}'.format(num, 5, num * 5))
f = print('{} x {:2} = {}'.format(num, 6, num * 6))
g = print('{} x {:2} = {}'.format(num, 7, num * 7))
h = print('{} x {:2} = {}'.format(num, 8, num * 8))
i = print('{} x {:2} = {}'.format(num, 9, num * 9))
j = print('{} x {} = {}'.format(num, 10, num * 10))
print('-' * 12)